services:
  - type: web
    name: ghibli-style-transfer
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p models
      wget -O models/ghibli_style.onnx [YOUR_MODEL_URL]
    startCommand: gunicorn --config gunicorn_config.py main:app
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
    plan: free
