services:
  - type: web
    name: ghibli-style-transfer
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p static/uploads
      mkdir -p model
    startCommand: gunicorn --worker-tmp-dir /dev/shm --workers=1 --threads=4 --timeout 120 main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
    plan: free
