services:
  - type: web
    name: ghibli-style-transfer
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p static/uploads static/outputs models
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 120 main:app
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
    plan: free
